apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nutrition-staging
resources:
  - namespace.yaml
  - secret-cloner.yaml
  - ../../base
patches:
  - path: env-patch.yaml
  - path: db-restore-patch.yaml
