apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nutrition-production
bases:
  - ../../base
resources:
  - db-backup-cronjob.yaml
patchesStrategicMerge:
  - env-patch.yaml
  - domain-patch.yaml
